sialyh/human_resources/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', views.human_resourcesView, name="human_resources"),
    path('applications', views.applicationsView, name="applications"),
    path('approvals', views.approvalsView, name="approvals"),
    path('application', views.applicationView, name="application"),
    path('disable_app/<int:app_id>/', views.disableApp, name="disable_application"),
    path('approval_app/<int:app_id>/', views.approveApp, name="approve_application"),
    path('consultation', views.consultation, name="consultation"),
    path('list_approval', views.list_approval_view, name="list_approval"),
    path('approval/<int:app_id>/', views.approvalView, name="approval"),

]  

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sialyh/login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', log_In, name="login"),
    path('logout', log_Out, name="logout"),
    path('rem_password', rem_password, name="rem_password"),

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sialyh/sialyh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sialyhapp.urls')),
    path('home/', include('sialyhapp.urls')),

    #Urls de app login
    path('login/', include('login.urls')),
    path('rem_password/', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    #Urls de app billing
    path('income/', include('billing.urls')),
    path('listings/', include('billing.urls')),
    path('disabled_item_invoice/', include('billing.urls')),
    path('invoices/', include('billing.urls')),
    path('export_invoices_excel/', include('billing.urls')),
    path('payDiscountslist/', include('billing.urls')),
    path('sepBonuseslist/', include('billing.urls')),
    path('disabled_item_sepBond/', include('billing.urls')),
    path('export_sepBonuses_to_excel/', include('billing.urls')),
    path('manual_invoices/', include('billing.urls')),
    path('sepBonuses/', include('billing.urls')),
    path('payDiscounts/', include('billing.urls')),
    path('export_payDiscounts_to_excel/', include('billing.urls')),
    path('disabled_item_payDiscount/', include('billing.urls')),
    path('dataManagement/', include('billing.urls')),
    path('dataManagementlist/', include('billing.urls')),
    path('export_dataManagement_to_excel/', include('billing.urls')),
    path('billing/', include('billing.urls')),
    
    #Url de app human_resources
    path('applications/', include('human_resources.urls')),
    path('application/', include('human_resources.urls')),
    path('approvals/', include('human_resources.urls')),
    path('approval/', include('human_resources.urls')),
    path('list_approval/', include('human_resources.urls')),
    path('approve_application/', include('human_resources.urls')),
    path('disable_application/', include('human_resources.urls')),
    path('consultation/', include('human_resources.urls')),
    path('human_resources/', include('human_resources.urls')),

    #Url de app accounting
    path('disabled_item_petty_cash/', include('accounting.urls')),
    path('petty_cash_list/', include('accounting.urls')),
    path('petty_cash/', include('accounting.urls')),
    path('listings_accounting/', include('accounting.urls')),
    path('income_accounting/', include('accounting.urls')),
    path('accounting/', include('accounting.urls')),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sialyh/human_resources/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User=get_user_model()

class applications (models.Model):

    name = models.CharField(max_length=64)
    idCard = models.PositiveIntegerField()
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    signature = models.TextField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    subtotal = models.IntegerField()
    total = models.IntegerField()
    approved = models.BooleanField(default=False)
    authorization = models.BooleanField(default=False)
    enabled = models.BooleanField(default=True)
    user_approved = models.ForeignKey(User, on_delete=models.CASCADE, related_name='approved_applications', null=True, blank=True)

    class Meta:
        db_table = 'applications'

class detApplications (models.Model):

    application = models.ForeignKey(applications, on_delete=models.CASCADE)
    reference = models.CharField(max_length=64)
    detail = models.CharField(max_length=64)
    amount = models.IntegerField()
    unitVal = models.IntegerField()
    totalVal = models.IntegerField()

    class Meta:
        db_table = 'detApplications'

sialyh/human_resources/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class form_application(forms.ModelForm):
    name = forms.CharField(
        label='NOMBRE ',
    )
    idCard = forms.IntegerField(
        label='CEDULA ',
    )
    date = forms.DateField(
        label='FECHA ',
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        input_formats=["%Y-%m-%d"],
        required=False,
    )
    subtotal = forms.IntegerField(
        label= 'SUB TOTAL',
    )
    total = forms.IntegerField(
        label = 'TOTAL',
    )
    
    authorization = forms.BooleanField(
        label= 'Autorizacion descuento'
    )

    class Meta:
        model = applications
        fields = ['name','idCard','date','subtotal','total','authorization']

class form_det_application(forms.ModelForm):

    reference = forms.CharField(
        label='Referencia'
    )
    detail = forms.CharField(
        label='Detalle'
    )
    amount = forms.IntegerField(
        label='Cantidad'
    )
    unitVal = forms.IntegerField(
        label='Valor unitario'
    )
    totalVal = forms.IntegerField(
        label='Valor total',
        disabled=True,
    )

    class Meta:
        model = detApplications
        fields = ['reference','detail','amount','unitVal','totalVal']


    
class application_filter_Form(forms.Form):
    user = forms.ModelChoiceField(
        label='Tienda',
        queryset=User.objects.all(),
        empty_label='Seleccione una tienda',
        required=False,
        )

sialyh/human_resources/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from .models import *
from django.contrib import messages
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from sialyhapp.functions import *
import base64



# Create your views here.

@login_required
def human_resourcesView(request):
    return render(request, "human_resources/human_resources.html")

@login_required
def applicationsView(request):
    return render(request, "human_resources/applications.html")

@login_required
def approvalsView(request):
    return render(request, "human_resources/approvals.html")

@login_required
def applicationView(request):
    if request.method == 'POST':
        # Informacion de la solicitud
        name = request.POST.get('name')
        idCard = request.POST.get('idCard')
        date = request.POST.get('date')
        user = request.user
        signature = request.POST.get('signature')
        subtotal = request.POST.get('subtotal')
        total = request.POST.get('total')
        authorization = request.POST.get('authorization') == 'on'

        application = applications(name=name, idCard=idCard, date=date, user=user, signature=signature, subtotal=subtotal, total=total, authorization=authorization)
        application.save()

        # Información del detalle de la solicitud
        references = request.POST.getlist('reference')
        details = request.POST.getlist('detail')
        amounts = request.POST.getlist('amount')
        unitVals = request.POST.getlist('unitVal')
        totalVals = request.POST.getlist('totalVal')

        # Verifica si se han enviado todos los detalles
        if len(references) == len(details) == len(amounts) == len(unitVals) == len(totalVals):
            for i in range(len(references)):
                detApplication = detApplications(
                    application=application, 
                    reference=references[i],
                    detail=details[i],
                    amount=amounts[i],
                    unitVal=unitVals[i],
                    totalVal=totalVals[i]
                )
                detApplication.save()
        else:
            return render(request, 'payroll_discounts/application.html', {'error': 'Por favor, complete todos los campos del detalle'})

        return redirect('application')
    else:
        return render(request, 'payroll_discounts/application.html')

@login_required
def list_approval_view(request):
    form_list_app = applications.objects.all()

    user_filter_formapp = application_filter_Form(request.GET)

    if user_filter_formapp.is_valid():
        user = user_filter_formapp.cleaned_data.get('user')

        if user:
            form_list_app = form_list_app.filter(user__username=user)
        return render (request, 'payroll_discounts/application_list.html', {
            'form_list_app':form_list_app,
            'user_filter_formapp':user_filter_formapp,
            })
            
    return render (request, 'payroll_discounts/application_list.html', {
        'form_list_app':form_list_app,
        'user_filter_formapp':user_filter_formapp,
        })

@login_required
def approvalView(request, app_id):
    try:
        formdet = detApplications.objects.filter(application_id=app_id)
        formapp = applications.objects.filter(id=app_id)
        encode_signature = applications.objects.get(id=app_id)
        signature = encode_signature.signature.split(',')[1]
    except:
        pass

    return render(request, "payroll_discounts/approval.html" , {
        'formapp':formapp,
        'formdet':formdet,
        'signature':signature,
    })



@login_required
def approveApp (request, app_id):
    application = applications.objects.get(id=app_id)
    application.approved = True
    application.user_approved = request.user
    application.save()
    return redirect ('approval')



@login_required
def disableApp (request, app_id):
    application = applications.objects.get(id=app_id)
    application.enabled = not application.enabled
    application.save()
    return redirect ('approval')


@login_required
def consultation (request):
    formapp = applications.objects.filter(user=request.user)
    return render (request, 'payroll_discounts/consultation.html', {'formapp':formapp})

sialyh/human_resources/templates/payroll_discounts/application.html
{% extends "sialyhapp/base2.html" %}

{% load static %}

<head>
    <!--Block head-->
    {% block head %}
    <script src="{% static 'vendor/jquery/jquery.js' %}"></script>
    {% endblock %}
    
</head>

{% block content %}


<!DOCTYPE html>
<html>

<section class="content">
    <div class="card">
        <div class="card-body">
            <div class="container-title">
                <div class="divTitle">
                    <h1>Solicitud de compra</h1>
                </div>
                <div class="divReturn">
                    <a href="{% url 'applications' %}" title="Facturas manuales" class="btn" style="background-color: grey; border-color: grey;">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                </div>
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="container-fluid" style="width: 100%;">
                    <div class="card">
                        <div class="card-body">
                            <table>
                                <tbody>
                                    <tr>
                                        <td><b><label for="name">NOMBRE:</label></b></td>
                                        <td><input type="text" id="name" name="name" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="idCard">CÉDULA:</label></b></td>
                                        <td><input type="number" id="idCard" name="idCard" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="date">FECHA:</label></b></td>
                                        <td><input type="date" id="date" name="date" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label>Descuento:</label></b></td>
                                        <td><b>35%</b></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="subtotal">Subtotal:</label></b></td>
                                        <td><input type="number" id="id_subtotal" name="subtotal" readonly required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="total">Total:</label></b></td>
                                        <td><input type="number" id="id_total" name="total" readonly required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="authorization">Autorización de descuento:</label></b></td>
                                        <td><input type="checkbox" id="authorization" name="authorization" required></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="container-fluid" style="width: 100%; margin-top: 2%;">
                    <div class="card">
                        <div class="card-body" id="formContainer">
                            <div class="table-responsive" id="formulario">
                                <table class="table-products">
                                    <tr>
                                        <td><b><label for="reference">Referencia:</label></b></td>
                                        <td><input type="text" id="id_reference" name="reference" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="detail">Detalle:</label></b></td>
                                        <td><input type="text" id="id_detail" name="detail" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="amount">Cantidad:</label></b></td>
                                        <td><input type="number" id="id_amount" name="amount" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="unitVal">Valor unitario:</label></b></td>
                                        <td><input type="number" id="id_unitVal" name="unitVal" required></td>
                                    </tr>
                                    <tr>
                                        <td><b><label for="totalVal">Valor total:</label></b></td>
                                        <td><input type="number" id="id_totalVal" name="totalVal" readonly required></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button id="addForm" type="button" style="background-color: grey; border-color: grey; border: 1px solid transparent; border-radius: 0.25rem;">
                                <i class="fas fa-duotone fa-plus"></i> &nbsp; Añadir producto
                            </button>
                            <button id="removeForm" type="button" style="background-color: grey; border-color: grey; border: 1px solid transparent; border-radius: 0.25rem;">
                                <i class="fas fa-duotone fa-minus"></i> &nbsp; Eliminar último producto
                            </button>
                        </div>
                    </div>
                </div>
                <div class="container-fluid" style="width: 100%; margin-top: 2%;">
                    <div class="card">
                        <div class="card-body">
                            <h1>Firma</h1>
                            <canvas id="canvas" style="margin-top: 2%; border: 1px solid #000;" required></canvas>
                            <input type="hidden" id="signatureInput" name="signature" required>
                            <div class="card-footer">
                                <button id="clearBtn" type="button" style="background-color: grey; border-color: grey; border: 1px solid transparent; border-radius: 0.25rem;">Limpiar</button>
                            </div>  
                        </div>
                    </div>
                </div>
                <button class="btn" style="background-color: grey; border-color: grey;" type="submit" method="POST">Enviar solicitud</button>
            </form>
        </div>
    </div>
</section>
<body>
    <script src="{% static 'JavaScript/Scripts.js' %}"></script>
</body>
</html>

{% endblock %}

sialyh/human_resources/templates/payroll_discounts/application_list.html
{% extends "sialyhapp/base2.html" %}

{% load static %}

<!--Block javascript-->
{% block javascript %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'datatables-1.10.20/js/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.js' %}"></script>
<script src="{% static 'datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.js' %}"></script>
<link rel="stylesheet" href="{% static 'datatables-1.10.20/css/dataTables.bootstrap4.css' %}" />
<link rel="stylesheet"
    href="{% static 'datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.css' %}" />

<script type="application/javascript">
    if ($.fn.DataTable.isDataTable('#tbl_applications')) {
        $('#tbl_applications').DataTable().destroy();
    }

    $('#tbl_applications').DataTable({
        responsive: true,
        autoWidth: false
    });
</script>

{% endblock %}


<head>
    <!--Block head-->
    {% block head %}
    <script src="{% static 'vendor/jquery/jquery.js' %}"></script>
    {% endblock %}
    
</head>

{% block content %}


<!DOCTYPE html>
<html>

<section class="content">
    <div class="card">
        <div class="card-body">
            <div class="container-title">
                <div class="divTitle">
                    <h1>Listado de solicitudes</h1>
                </div>
                <div class="divReturn">
                    <a href="{% url 'human_resources' %}" title="Facturas manuales" class="btn" style="background-color: grey; border-color: grey;">
                        <i class="fas fa-arrow-left"></i>
                    </a>
                </div>
            </div>
            <div class="container-fluid">
                <div class="container-fluid">
                    <form method="get">
                        {{ user_filter_formapp.as_p }}
                        <button type="submit" class="btn btn-success" style="background-color: grey; border-color: grey;">
                            Filtrar
                        </button>
                    </form>
                </div>
            </div>
            <div class="container-fluid" style="width: 100%;">
                <div class="card">
                    <div class="card-body">
                        <table class="table" id="tbl_applications">
                            <thead>
                                <tr>
                                    <th><strong>Solicitud</strong></th>
                                    <th><strong>Empleado</strong></th>
                                    <th><strong>Cedula</strong></th>
                                    <th><strong>Tienda</strong></th>
                                    <th><strong>Valor</strong></th>
                                    <th><strong>Estado</strong></th>
                                    <th><strong>Opciones</strong></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for application in form_list_app %}
                                <tr>
                                    <td> {{ application.id }} </td>
                                    <td> {{ application.name }} </td>
                                    <td> {{ application.idCard }} </td>
                                    <td> {{ application.user }} </td>
                                    <td> $ {{ application.total }} </td>
                                    {% if application.approved %}
                                    <td> Aprobado </td>
                                    {% elif not application.enabled %}
                                    <td> No aprobado </td>
                                    {% else %}
                                    <td> Pendiente </td>
                                    {% endif %}
                                    <td>
                                        {% if not application.approved and application.enabled %}
                                        <a href="{% url 'approve_application' application.id %}" title="Aprobar" class="btn" style="background-color: grey; border-color: grey;">
                                            <i class="fas fa-check"></i>
                                        </a>
                                        <a href="{% url 'disable_application' application.id %}" title="No aprobar" class="btn" style="background-color: grey; border-color: grey;">
                                            <i class="fas fa-times"></i>
                                        </a>
                                        {% endif %}
                                        <a href="{% url 'approval' application.id %}" title="Ver solicitud" class="btn" style="background-color: grey; border-color: grey;">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
<script src="{% static 'JavaScript/Scripts.js' %}"></script>

</body>
</html>

{% endblock %}

sialyh/human_resources/templates/payroll_discounts/approval.html
{% extends "sialyhapp/base2.html" %}

{% load static %}

<head>
    <!--Block head-->
    {% block head %}


    {% endblock %}
    
</head>


{% block content %}

<html>
<body>

    <section class="content">
        <div class="container-title">
            <div class="divTitle">
                <h1>Solicitud de descuento por nómina</h1>
            </div>
            <div class="divReturn">
                <a href="{% url 'list_approval' %}" title="Volver" class="btn" style="background-color: grey; border-color: grey;">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </div>
        </div>
        <div class="col-12">
            <div class="invoice p-3 mb-3">
                <div class="container-fluid" style="text-align: center;">
                    <h1>COTIZACIÓN DESCUENTO DE MERCANCÍAS</h1>
                    <P> <strong> NOTA: </strong> Esta mercancía es para el uso exclusivo del empleado al servicio de SARALUZ S.A.S o de sus
                        familiares (padres, cónyuge e hijos). Si se comprobase un destino diferente al mencionado será causal de Cancelación 
                        del contrato por justa causa.
                    </P>
                </div>
                <div class="container-fluid">
                    <div class="container-fluid">
                        <table>
                            {% for application in formapp %}
                            <tr>
                                <th> <Strong> NOMBRE: </Strong></th>
                                <td>{{application.name}}</td>
                            </tr>
                            <tr>
                                <th><strong> CEDULA: </strong></th>
                                <td>{{application.idCard}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                        <hr>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th><strong>Ref.</strong></th>
                                    <th><strong>Detalle</strong></th>
                                    <th><strong>Cantidad</strong></th>
                                    <th><strong>Vr. Unitario</strong></th>
                                    <th><strong>Vr. Total</strong></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for detapplication in formdet %}
                                <tr>
                                    <td>
                                        {{detapplication.reference}}
                                    </td>
                                    <td>
                                        {{detapplication.detail}}
                                    </td>
                                    <td>
                                        {{detapplication.amount}}
                                    </td>
                                    <td>
                                        $ {{detapplication.unitVal}}
                                    </td>
                                    <td>
                                        $ {{detapplication.totalVal}}
                                    </td>
                                </tr>
                                {% endfor %}
                                {% for applicationVal in formapp %}
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th>Sub Total:</th>
                                    <td>$ {{ applicationVal.subtotal}}</td>
                                </tr>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th>Total:</th>
                                    <td>$ {{ applicationVal.total}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% for applicationsign in formapp %}
                        <table class="table table-bordered" style="border: 0px solid #ffffff;">
                            <tr>
                                <th style="text-align: right;border: 0px solid #ffffff;">Fecha: </th>
                                <td style="border: 0px solid #ffffff;">{{applicationsign.date}}</td>
                                <th style="text-align: right;border: 0px solid #ffffff;">Vo.Bo.Of.</th>
                                <td style="border: 0px solid #ffffff;">{{applicationsign.user_approved.first_name}} &nbsp; {{applicationsign.user_approved.last_name}} </td>
                                <th style="text-align: right;border: 0px solid #ffffff;">Almacen:</th>
                                <td style="border: 0px solid #ffffff;">{{applicationsign.user}}</td>
                            </tr>
                            <tr>
                                <th style="text-align: right;border: 0px solid #ffffff;">Firma: </th>
                                <td style="border: 0px solid #ffffff; max-width: 0px;"><img src="data:image/png;base64,{{ signature }}"></td>
                                <th style="text-align: right;border: 0px solid #ffffff;">Descuento:</th>
                                <td style="border: 0px solid #ffffff;">35%</td>
                            </tr>
                        </table>
                        {% if not applicationsign.approved %}
                        <table class="table table-bordered" style="border: 0px solid #ffffff;">
                            <tr>
                                <td style="border: 0px solid #ffffff; text-align: right;">
                                    <a href="{% url 'approve_application' applicationsign.id %}"><button type="button" style="background-color: grey; border-color: grey; border: 1px solid transparent; border-radius: 0.25rem;">Aprobado</button></a>
                                </td>
                                <td style="border: 0px solid #ffffff;">
                                    <a href="{% url 'disable_application' applicationsign.id %}"><button type="button" style="background-color: grey; border-color: grey; border: 1px solid transparent; border-radius: 0.25rem;">No aprobado</button></a>
                                </td>
                            </tr>
                        </table>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

{% endblock %}