sialyh/billing/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', views.billingView, name="billing"),
    path('income', views.incomeView, name="income"),
    path('listings', views.listingsView, name="listings"),
    path('income/manual_invoices', views.manual_invoicesView, name="manual_invoices"),
    path('income/sepBonuses', views.sep_bonusesView, name="sepBonuses"),
    path('income/payDiscounts', views.pay_discountsView, name="payDiscounts"),
    path('income/dataManagement', views.data_managementView, name="dataManagement"),
    path('listings/dataManagementlist', views.dataManagement_list, name="dataManagementlist"),
    path('listings/dataManagement/export_dataManagement_to_excel', views.export_dataManagement_to_excel, name="export_dataManagement_to_excel"),
    path('listings/invoices', views.invoice_list, name="invoices"),
    path('listings/invoices/export_invoices_excel', views.export_invoices_to_excel, name="export_invoices_excel"),
    path('listings/invoices/disabled_item/<int:invoice_id>/', views.disable_item_manInvoice, name="disabled_item_invoice"),
    path('listings/sepBonuseslist', views.sepBonuses_list, name="sepBonuseslist"),
    path('listings/sepBonuseslist/export_sepBonuses_to_excel', views.export_sepBonuses_to_excel, name="export_sepBonuses_to_excel"),
    path('listings/sepBonuseslist/disabled_item_sepBond/<int:bond_id>/', views.disable_item_sepBonuses, name="disabled_item_sepBond"),
    path('listings/payDiscountslist', views.payDiscounts_list, name="payDiscountslist"),
    path('listings/payDiscountslist/export_payDiscounts_to_excel', views.export_payDiscounts_to_excel, name="export_payDiscounts_to_excel"),
    path('listings/payDiscountslist/disabled_item_payDiscount/<int:payd_id>/', views.disable_item_payDiscount, name="disabled_item_payDiscount"),
]   
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sialyh/login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', log_In, name="login"),
    path('logout', log_Out, name="logout"),
    path('rem_password', rem_password, name="rem_password"),

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sialyh/sialyh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sialyhapp.urls')),
    path('home/', include('sialyhapp.urls')),

    #Urls de app login
    path('login/', include('login.urls')),
    path('rem_password/', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    #Urls de app billing
    path('income/', include('billing.urls')),
    path('listings/', include('billing.urls')),
    path('disabled_item_invoice/', include('billing.urls')),
    path('invoices/', include('billing.urls')),
    path('export_invoices_excel/', include('billing.urls')),
    path('payDiscountslist/', include('billing.urls')),
    path('sepBonuseslist/', include('billing.urls')),
    path('disabled_item_sepBond/', include('billing.urls')),
    path('export_sepBonuses_to_excel/', include('billing.urls')),
    path('manual_invoices/', include('billing.urls')),
    path('sepBonuses/', include('billing.urls')),
    path('payDiscounts/', include('billing.urls')),
    path('export_payDiscounts_to_excel/', include('billing.urls')),
    path('disabled_item_payDiscount/', include('billing.urls')),
    path('dataManagement/', include('billing.urls')),
    path('dataManagementlist/', include('billing.urls')),
    path('export_dataManagement_to_excel/', include('billing.urls')),
    path('billing/', include('billing.urls')),
    
    #Url de app human_resources
    path('applications/', include('human_resources.urls')),
    path('application/', include('human_resources.urls')),
    path('approvals/', include('human_resources.urls')),
    path('approval/', include('human_resources.urls')),
    path('list_approval/', include('human_resources.urls')),
    path('approve_application/', include('human_resources.urls')),
    path('disable_application/', include('human_resources.urls')),
    path('consultation/', include('human_resources.urls')),
    path('human_resources/', include('human_resources.urls')),

    #Url de app accounting
    path('disabled_item_petty_cash/', include('accounting.urls')),
    path('petty_cash_list/', include('accounting.urls')),
    path('petty_cash/', include('accounting.urls')),
    path('listings_accounting/', include('accounting.urls')),
    path('income_accounting/', include('accounting.urls')),
    path('accounting/', include('accounting.urls')),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sialyh/billing/models.py
from django.db import models
from django.contrib.auth import get_user_model
from sialyhapp.functions import *

User=get_user_model()

# Create your models here.

#Este es el modelo de la tabla de las facturas manuales en base de datos (manInvoices)
class manInvoice(models.Model):
    numInvoice=models.PositiveIntegerField()
    dateInvoice=models.DateField(null=True,blank=True)
    file=models.FileField(max_length=200)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    enabled=models.BooleanField(default=True)

    class Meta:
        db_table='manInvoice'



#Este es el modelo de la tabla de los descuentos por nómina en base de datos (payDiscounts)
class payDiscounts(models.Model):
    numInvoice=models.PositiveIntegerField()
    datePayDiscounts=models.DateField(null=True,blank=True)
    file=models.FileField(max_length=200)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    enabled=models.BooleanField(default=True)

    class Meta:
        db_table='payDiscounts'


#Este es el modelo de la tabla de los bonos de separado en base de datos (sepBonuses)
class sepBonuses(models.Model):
    numBond=models.PositiveBigIntegerField()
    dateInvoice=models.DateField(null=True,blank=True)
    valBond=models.PositiveIntegerField()
    file=models.FileField(max_length=200)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    enabled=models.BooleanField(default=True)

    class Meta :
        db_table='sepBonuses'


#Este es el modelo de la tabla de manejo de datos en base de datos (dataManagement)
class dataManagement(models.Model):
    idCard=models.PositiveIntegerField()
    file=models.FileField(max_length=200)
    created=models.DateField(auto_now=True)
    updated=models.DateField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    enabled=models.BooleanField(default=True)

    class Meta:
        db_table='dataManagement'

sialyh/billing/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib import messages
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from openpyxl import *
from datetime import datetime
from sialyhapp.functions import *


# Create your views here.

# ACA VAN LAS VISTAS PARA LOS MODULOS DE INGRESOS Y LISTADOS

# Esta es la vista de la seccion de facturacion en el Home
@login_required
def billingView(request):
    return render(request, "billing/billing.html")


# Esta es la vista que renderiza las opciones para los ingresos
@login_required
def incomeView(request):
    return render(request, "billing/income.html")


# Esta es la vista que renderiza las opciones para los listados
@login_required
def listingsView(request):
    return render(request, "billing/listings.html")


# ACA VAN LAS VISTAS DE LOS FORMULARIOS DE INGRESO DE DOCUMENTOS

# Esta es la vista del formulario de ingreso de facturas manuales
@login_required
def manual_invoicesView(request):
    if request.method == 'POST':
        form = form_manual_billing(request.POST, request.FILES)
        if form.is_valid():
            man_invoice = form.save(commit=False, user=request.user)
            man_invoice.user = request.user
            man_invoice.save()
            messages.success(request, 'Información enviada correctamente.')
            return redirect('manual_invoices')
    else:
        form = form_manual_billing()
    return render(request, 'manual_invoices/manual_invoices.html', {'form': form})


# Esta es la vista del formulario de ingreso de bonos de separado
@login_required
def sep_bonusesView(request):
    if request.method == 'POST':
        formsb = form_separated_bonuses(request.POST, request.FILES)
        if formsb.is_valid():
            separated_bond = formsb.save(commit=False, user=request.user)
            separated_bond.user = request.user
            separated_bond.save()
            messages.success(request, 'Información enviada correctamente.')
            return redirect('sepBonuses')
    else:
        formsb = form_separated_bonuses()
    return render(request, 'separate_bonuses/separate_bonuses.html', {'formsb': formsb})


# Esta es la vista del formulario de ingreso de descuentos por nomina
@login_required
def pay_discountsView(request):
    if request.method == 'POST':
        formpp = form_payroll_discount(request.POST, request.FILES)
        if formpp.is_valid():
            payroll_discount = formpp.save(commit=False, user=request.user)
            payroll_discount.user = request.user
            payroll_discount.save()
            messages.success(request, 'Información enviada correctamente.')
            return redirect('payDiscounts')
    else:
        formpp = form_payroll_discount()
    return render(request, 'payroll_discounts/payroll_discounts.html', {'formpp': formpp})


#Esta es la vista del formulario de ingreso de manejo de datos
@login_required
def data_managementView(request):
    # Lógica para el formulario de envío de datos
    if request.method == 'POST':
        formdm = form_data_management(request.POST, request.FILES)
        if formdm.is_valid():
            data_management = formdm.save(commit=False, user=request.user)
            data_management.user = request.user
            data_management.save()
            messages.success(request, 'Información enviada correctamente.')
            return redirect('dataManagement')
    else:
        formdm = form_data_management()
    return render(request, 'data_management/data_management.html', {'formdm': formdm})


# ACA VAN LAS VISTAS DE LOS LISTADOS DE LOS DOCUMENTOS INGRESADOS

# Esta es la vista del listado de facturas manuales
@login_required
def invoice_list(request):
    miForm = manInvoice.objects.all()
    # Aca se inicializan los formularios de filtro
    date_invoice_filter_form = invoice_date_filterForm(request.GET)
    user_filter_form = user_filterForm(request.GET)
    # Aca se verifica si los formularios son válidos
    if date_invoice_filter_form.is_valid() and user_filter_form.is_valid():
        date_invoice = date_invoice_filter_form.cleaned_data.get('dateInvoice')
        user_filter = user_filter_form.cleaned_data.get('user')
        # Aca se filtra el queryset de manInvoice
        if date_invoice:
            miForm = miForm.filter(dateInvoice=date_invoice)
        if user_filter:
            miForm = miForm.filter(user__username=user_filter)
        # Aca se renderiza la plantilla con los objetos filtrados y los formularios de filtro
        return render(request, 'manual_invoices/invoices.html', {
            'miForm': miForm,
            'date_invoice_filter_form': date_invoice_filter_form,
            'user_filter_form': user_filter_form,
            'filtered_date': date_invoice,
            'filtered_user': user_filter,
        })
    else:
        return render(request, 'manual_invoices/invoices.html', {
            'miForm': miForm,
            'date_invoice_filter_form': date_invoice_filter_form,
            'user_filter_form': user_filter_form,
        })


# Esta es la vista del listado de bonos de separado
@login_required
def sepBonuses_list(request):
    miFormsb = sepBonuses.objects.all()
    # Aca se inicializan los formularios de filtro
    date_invoice_filter_formsb = invoice_date_filterFormsb(request.GET)
    user_filter_formsb = user_filterFormsb(request.GET)
    # Aca se verifica si los formularios son válidos
    if date_invoice_filter_formsb.is_valid() and user_filter_formsb.is_valid():
        date_invoice = date_invoice_filter_formsb.cleaned_data.get('dateInvoice')
        user_filter = user_filter_formsb.cleaned_data.get('user')
        # Aca se filtra el queryset de sepBonuses
        if date_invoice:
            miFormsb = miFormsb.filter(dateInvoice=date_invoice)
        if user_filter:
            miFormsb = miFormsb.filter(user__username=user_filter)
        return render(request, 'separate_bonuses/separate_bonuses_list.html', {
            'miFormsb': miFormsb,
            'date_invoice_filter_formsb': date_invoice_filter_formsb,
            'user_filter_formsb': user_filter_formsb,
            'filtered_date': date_invoice,
            'filtered_user': user_filter,
        })
    else:
        # Aca se renderiza la plantilla con los objetos filtrados y los formularios de filtro
        return render(request, 'separate_bonuses/separate_bonuses_list.html', {
            'miFormsb': miFormsb,
            'date_invoice_filter_formsb': date_invoice_filter_formsb,
            'user_filter_formsb': user_filter_formsb, })


# Esta es la vista del listado de los descuentos por nómina
@login_required
def payDiscounts_list(request):
    miFormpd = payDiscounts.objects.all()
    # Aca se inicializan los formularios de filtro
    date_invoice_filter_formpd = invoice_date_filterFormpd(request.GET)
    user_filter_formpd = user_filterFormpd(request.GET)
    # Aca se verifica si los formularios son válidos
    if date_invoice_filter_formpd.is_valid() and user_filter_formpd.is_valid():
        date_invoice = date_invoice_filter_formpd.cleaned_data.get('datePayDiscounts')
        user_filter = user_filter_formpd.cleaned_data.get('user')
        # Aca se filtra el queryset de sepBonuses
        if date_invoice:
            miFormpd = miFormpd.filter(datePayDiscounts=date_invoice)
        if user_filter:
            miFormpd = miFormpd.filter(user__username=user_filter)
        return render(request, 'payroll_discounts/payroll_discounts_list.html', {
            'miFormpd': miFormpd,
            'date_invoice_filter_formpd': date_invoice_filter_formpd,
            'user_filter_formpd': user_filter_formpd,
            'filtered_date': date_invoice,
            'filtered_user': user_filter,
        })
    # Aca se renderiza la plantilla con los objetos filtrados y los formularios de filtro
    return render(request, 'payroll_discounts/payroll_discounts_list.html', {
        'miFormpd': miFormpd,
        'date_invoice_filter_formpd': date_invoice_filter_formpd,
        'user_filter_formpd': user_filter_formpd, })


# Esta es la vista del listado de manejo de datos personales
@login_required
def dataManagement_list(request):
    miFormdm = dataManagement.objects.all()
    # Aca se inicializan los formularios de filtro
    date_filter_formdm = date_filterFormdm(request.GET)
    user_filter_formdm = user_filterFormdm(request.GET)

    # Aca se verifica si los formularios son válidos
    if date_filter_formdm.is_valid() and user_filter_formdm.is_valid():
        date = date_filter_formdm.cleaned_data.get('date')
        user = user_filter_formdm.cleaned_data.get('user')

        # Aca se filtra el queryset de sepBonuses
        if date:
            miFormdm = miFormdm.filter(created=date)
        if user:
            miFormdm = miFormdm.filter(user__username=user)

        return render(request, 'data_management/data_management_list.html', {
            'miFormdm': miFormdm,
            'date_filter_formdm': date_filter_formdm,
            'user_filter_formdm': user_filter_formdm,
            'filtered_date': date,
            'filtered_user': user,
        })
    # Aca se renderiza la plantilla con los objetos filtrados y los formularios de filtro
    return render(request, 'data_management/data_management_list.html', {
        'miFormdm': miFormdm,
        'date_filter_formdm': date_filter_formdm,
        'user_filter_formdm': user_filter_formdm,})


# ACA VAN LAS VISTAS PARA DESHABILITAR LOS ITEMS DE LOS LISTADOS

# Esta es la vista para deshabilitar items de las facturas manuales
@login_required
def disable_item_manInvoice(request, invoice_id):
    invoice = manInvoice.objects.get(id=invoice_id)
    invoice.enabled = not invoice.enabled
    invoice.save()
    return redirect('invoices')

sialyh/billing/templates/billing/billing.html
{% extends "sialyhapp/base.html" %}

{% load static %}

{% block content %}

<html>

<body>
    <hr>
    <section class="content">
        <div class="container-fluid" style="width: 100%;">
            <H1></H1>
            <div class="row" style="justify-content: center;">
                    {% if perms.sialyhapp.view_incomes %}
                    <div class="col-5" style="margin: 1rem; max-width: min-content;">
                        <div class="card" style="margin: 1rem; max-width: min-content;">
                            <div class="card-body" style="text-align: center;">
                                <a href="{% url 'income' %}" title="Ingreso de documentos">
                                    <img src="{% static 'img/upload.png' %}" width="80px" alt="Ingreso de documentos"></img>
                                </a>
                            </div>
                            <div class="card-footer" style="text-align: center;">
                                <p style="color: black;">Ingreso</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if perms.sialyhapp.view_listings %}
                    <div class="col-5" style="margin: 1rem; max-width: min-content;">
                        <div class="card" style="margin: 1rem; max-width: min-content;">
                            <div class="card-body" style="text-align: center;">
                                <a href="{% url 'listings' %}" title="Listado de documentos">
                                    <img src="{% static 'img/listado.png' %}" width="80px" alt="Listado de documentos"></img>
                                </a>
                            </div>
                            <div class="card-footer" style="text-align: center;">
                                <p style="color: black;">Listados</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
</body>

</html>

{% endblock %}

sialyh/billing/templates/billing/income.html
{% extends "sialyhapp/base2.html" %}

{% load static %}

<head>
    <!--Block head-->
    {% block head %}


    {% endblock %}
    
</head>


{% block content %}
<html>
    <html>
        <body>
            <hr>
            <section>
                <div class="container-title" >
                    <div  class="divTitle" style="text-align: center;">
                        <h1>Ingreso de documentos</h1>
                    </div>
                    <div class="divReturn">
                        <a href="{% url 'billing' %}" title="Volver" class="btn" style="background-color: grey; border-color: grey;">
                            <i class="fas far fa-arrow-left"></i>
                        </a>
                    </div>
                </div>
            </section>
            <hr>
            <section class="content">
                <div class="container-fluid"  style="width: 100%;">
                    <div class="row" style="justify-content: center;">
                        {% if perms.sialyhapp.view_maninvoices %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'manual_invoices' %}" title="Facturas manuales">
                                        <img src="{% static 'img/man_invoice.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Facturas manuales</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.sialyhapp.view_sepbonuses %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'sepBonuses' %}" title="Bonos de separado">
                                        <img src="{% static 'img/sep_bond.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Bonos de separado</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.sialyhapp.view_paydiscount %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'payDiscounts' %}" title="Descuentos por nómina">
                                        <img src="{% static 'img/consignment.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Descuentos por nómina</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.sialyhapp.view_datamanagement %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'dataManagement' %}" title="Manejo de datos personales">
                                        <img src="{% static 'img/data_management.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Manejo datos</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </section>
        </body>
    </html>
    

</html>
{% endblock %}

<!--Bloque de listado-->
{% block listing %}


{% endblock %}

sialyh/billing/templates/billing/listings.html
{% extends "sialyhapp/base2.html" %}

{% load static %}

<head>
    <!--Block head-->
    {% block head %}


    {% endblock %}
    
</head>


{% block content %}
<html>

    <html>
        <body>
            <hr>
            <section>
                <div class="container-title">
                    <div class="divTitle" style="text-align: center;">
                        <h1>Listados</h1>
                    </div>
                    <div class="divReturn">
                        <a href="{% url 'billing' %}" title="Volver" class="btn" style="background-color: grey; border-color: grey;">
                            <i class="fas far fa-arrow-left"></i>
                        </a>
                    </div>
                </div>
            </section>
            <hr>
            <section class="content">
                <div class="container-fluid"  style="width: 100%;">
                    <div class="row" style="justify-content: center;">
                        {% if perms.sialyhapp.view_listinvoices %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'invoices' %}" title="Facturas manuales">
                                        <img src="{% static 'img/man_invoice.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Facturas manuales</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.sialyhapp.view_listsepbonuses %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'sepBonuseslist' %}" title="Bonos de separado">
                                        <img src="{% static 'img/sep_bond.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Bonos de separado</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.sialyhapp.view_listpaydiscount %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'payDiscountslist' %}" title="Descuentos por nómina">
                                        <img src="{% static 'img/consignment.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Descuentos por nómina</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if perms.sialyhapp.view_listdatamanagement %}
                        <div class="col-5" style="margin: 1rem; max-width: min-content;">
                            <div class="card" style="margin: 1rem; max-width: min-content;">
                                <div class="card-body" style="text-align: center;">
                                    <a href="{% url 'dataManagementlist' %}" title="Manejo de datos personales">
                                        <img src="{% static 'img/data_management.png' %}" width="80px"></img>
                                    </a>
                                </div>
                                <div class="card-footer"style="text-align: center;">
                                    <p style="color: black;">Manejo datos</p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </section>
        </body>
    </html>
    

</html>
{% endblock %}